services:
  postgres:
    image: postgres:15-alpine
    container_name: stock-notebook-postgres-dev
    environment:
      POSTGRES_DB: stock_notebook
      POSTGRES_USER: stock_user
      POSTGRES_PASSWORD: stock_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - stock-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stock_user -d stock_notebook"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:4.8.1
    container_name: stock-notebook-adminer-dev
    ports:
      - "8081:8080"
    networks:
      - stock-network
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: hydra

  backend:
    build:
      context: ./backend-java
      dockerfile: Dockerfile
      target: development
    container_name: stock-notebook-backend-dev
    ports:
      - "8080:8080"
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: stock_notebook
      DATABASE_USER: stock_user
      DATABASE_PASSWORD: stock_password
      JWT_SECRET: dev-jwt-secret-key
      LOG_LEVEL: DEBUG
      CORS_ALLOWED_ORIGINS: http://localhost:3000
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - stock-network
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./backend-java/src:/app/src:ro
      - ./backend-java/target:/app/target
    develop:
      watch:
        - action: rebuild
          path: ./backend-java/src
        - action: rebuild
          path: ./backend-java/pom.xml
        - action: rebuild
          path: ./backend-java/src/main/resources

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile.dev
    container_name: stock-notebook-nginx-dev
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - stock-network
    restart: unless-stopped
    volumes:
      - ./frontend/build:/var/www/html:ro

volumes:
  postgres_data_dev:
    driver: local
  node_modules:
    driver: local

networks:
  stock-network:
    driver: bridge
