services:
  postgres:
    image: postgres:15-alpine
    container_name: stock-notebook-postgres-dev
    environment:
      POSTGRES_DB: stock_notebook
      POSTGRES_USER: stock_user
      POSTGRES_PASSWORD: stock_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - stock-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stock_user -d stock_notebook"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:4.8.1
    container_name: stock-notebook-adminer-dev
    ports:
      - "8081:8080"
    networks:
      - stock-network
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: hydra

  backend:
    build:
      context: ./backend-java
      dockerfile: Dockerfile.dev
    image: stock-notebook-backend:dev
    container_name: stock-notebook-backend-dev
    ports:
      - "8080:8080"
    environment:
      # Database configuration
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: stock_notebook
      DATABASE_USER: stock_user
      DATABASE_PASSWORD: stock_password

      # Application configuration
      JWT_SECRET: dev-jwt-secret-key-that-is-at-least-256-bits-long-for-security-requirements
      LOG_LEVEL: DEBUG
      CORS_ALLOWED_ORIGINS: http://localhost:3000
      SPRING_PROFILES_ACTIVE: docker

      # JVM configuration (overrides Dockerfile defaults if needed)
      JAVA_OPTS: "-Xmx512m -Xms256m -XX:+UseG1GC -Dspring.devtools.restart.enabled=true"
    networks:
      - stock-network
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      # Mount source code for hot reload during development
      - ./backend-java/src:/app/src:ro
      - ./backend-java/target:/app/target
      - ./backend-java/pom.xml:/app/pom.xml:ro
    develop:
      watch:
        - action: rebuild
          path: ./backend-java/src
          ignore:
            - ./backend-java/src/test
        - action: rebuild
          path: ./backend-java/pom.xml
        - action: rebuild
          path: ./backend-java/src/main/resources
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      start_period: 60s
      retries: 3

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile.dev
    image: stock-notebook-nginx:dev
    container_name: stock-notebook-nginx-dev
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - stock-network
    restart: unless-stopped
    volumes:
      - ./frontend/build:/var/www/html:ro

volumes:
  postgres_data_dev:
    driver: local
    name: stock-notebook-postgres-data-dev

networks:
  stock-network:
    driver: bridge
    name: stock-notebook-network
